(function () {
  "use strict";

  window.EZTRIP_DEMO = {
    meta: {
      id: "beijing-two-day-rain-hitl-v1",
      generatedAt: "2026-08-27T13:50:31+08:00",
      dataMode: "demo",
      disclosure: "本页面使用演示数据；价格仅供行程预算参考。",
    },
    request: {
      rawInput:
        "9月3日从上海出发去北京，两位成人玩两天，整趟预算3000元。想多看看历史文化类景点，尽量少步行，行程轻松一点。",
      destination: "北京",
      origin: "上海",
      startDate: "2026-09-03",
      days: 2,
      adults: 2,
      budget: 3000,
      pace: "轻松",
      preferences: ["历史文化", "少走路"],
    },
    versions: {
      v1: {
        label: "原方案",
        status: "等待确认",
        days: [
          {
            id: "day-1",
            number: 1,
            date: "9月3日",
            weekday: "周四",
            departure: "建议 08:57 从住宿地点出发前往首站",
            weather: {
              label: "有阵雨",
              impact: "室内与混合型活动，无需替换",
            },
            items: [
              {
                id: "national-museum",
                time: "09:00 — 11:00",
                title: "中国国家博物馆",
                district: "东城区",
                environment: "室内",
                ticket: "门票免费",
                route: "从住宿地点出发：3 分钟 · 930 米",
                description: "从中国历史与城市记忆开始这趟旅程。",
                reason: "首日优先室内或混合型活动。",
                source: "演示数据 · 2026/08/21",
              },
              {
                id: "palace-museum",
                time: "13:00 — 15:00",
                title: "故宫博物院",
                district: "东城区",
                environment: "室内 / 户外混合",
                ticket: "门票参考 ¥60/人",
                route: "从上一站出发：5 分钟 · 1,670 米",
                description: "下午留给故宫，步调从容，不赶场。",
                reason: "候选命中已确认的用户硬约束。",
                source: "演示数据 · 2026/08/21",
              },
            ],
          },
          {
            id: "day-2",
            number: 2,
            date: "9月4日",
            weekday: "周五",
            departure: "建议 09:51 从住宿地点出发前往首站",
            weather: {
              label: "有阵雨",
              impact: "2 项户外活动建议调整",
            },
            items: [
              {
                id: "temple-of-heaven",
                time: "10:00 — 12:00",
                title: "天坛公园",
                district: "东城区",
                environment: "户外",
                ticket: "门票参考 ¥15–¥34/人",
                route: "从住宿地点出发：9 分钟 · 3,050 米",
                description: "上午游览中轴线南段的代表性建筑群。",
                reason: "候选命中已确认的用户必去地点。",
                source: "演示数据 · 2026/08/21",
                affectedByRain: true,
              },
              {
                id: "jingshan-park",
                time: "13:00 — 15:00",
                title: "景山公园",
                district: "西城区",
                environment: "户外",
                ticket: "门票参考 ¥2/人",
                route: "从上一站出发：16 分钟 · 5,750 米",
                description: "下午登高看北京城，作为两日行程收尾。",
                reason: "候选补充北京历史文化体验。",
                source: "演示数据 · 2026/08/21",
                affectedByRain: true,
              },
            ],
          },
        ],
      },
      v2: {
        label: "调整后",
        status: "调整后 · 等待确认",
        changedDates: 1,
        protectedDays: ["day-1"],
        days: [
          {
            id: "day-1",
            number: 1,
            date: "9月3日",
            weekday: "周四",
            departure: "建议 08:57 从住宿地点出发前往首站",
            weather: {
              label: "有阵雨",
              impact: "室内与混合型活动，无需替换",
            },
            items: [
              {
                id: "national-museum",
                time: "09:00 — 11:00",
                title: "中国国家博物馆",
                district: "东城区",
                environment: "室内",
                ticket: "门票免费",
                route: "从住宿地点出发：3 分钟 · 930 米",
                description: "从中国历史与城市记忆开始这趟旅程。",
                reason: "首日优先室内或混合型活动。",
                source: "演示数据 · 2026/08/21",
              },
              {
                id: "palace-museum",
                time: "13:00 — 15:00",
                title: "故宫博物院",
                district: "东城区",
                environment: "室内 / 户外混合",
                ticket: "门票参考 ¥60/人",
                route: "从上一站出发：5 分钟 · 1,670 米",
                description: "下午留给故宫，步调从容，不赶场。",
                reason: "候选命中已确认的用户硬约束。",
                source: "演示数据 · 2026/08/21",
              },
            ],
          },
          {
            id: "day-2",
            number: 2,
            date: "9月4日",
            weekday: "周五",
            departure: "建议 09:51 从住宿地点出发前往首站",
            weather: {
              label: "有阵雨",
              impact: "已采用全天室内方案",
            },
            items: [
              {
                id: "capital-museum",
                time: "10:00 — 12:00",
                title: "首都博物馆",
                district: "西城区",
                environment: "室内",
                ticket: "门票免费",
                route: "距原地点直线约 6.3 公里 · 路线随方案调整",
                description: "在室内了解北京城市发展的完整脉络。",
                reason: "替换受降雨影响的天坛公园。",
                source: "演示数据 · 雨天方案",
                replacementFor: "天坛公园",
              },
              {
                id: "beijing-planetarium",
                time: "13:00 — 15:00",
                title: "北京天文馆",
                district: "西城区",
                environment: "室内",
                ticket: "门票参考 ¥10–¥20/人",
                route: "同在西城区 · 路线随方案调整",
                description: "以室内天文体验替代雨中的登高行程。",
                reason: "替换受降雨影响的景山公园。",
                source: "演示数据 · 雨天方案",
                replacementFor: "景山公园",
              },
            ],
          },
        ],
      },
    },
    rainProposal: {
      title: "全天室内方案",
      summary: "当天 2 个受天气影响的活动将一起调整",
      replacements: [
        {
          from: "天坛公园",
          to: "首都博物馆",
          reason: "室内场馆 · 距原地点直线约 6.3 公里",
        },
        {
          from: "景山公园",
          to: "北京天文馆",
          reason: "室内场馆 · 同在西城区",
        },
      ],
      scope: "保留第 1 天，仅替换第 2 天的两项户外活动。",
    },
    budgets: {
      v1: {
        midpoint: 1370,
        minimum: 924,
        maximum: 1822,
        items: [
          {
            category: "住宿",
            detail: "前门示例住宿 · 1 间夜",
            minimum: 350,
            maximum: 550,
          },
          {
            category: "交通",
            detail: "4 个活动 · 按每人 6 段市内出行估算",
            minimum: 60,
            maximum: 300,
          },
          {
            category: "餐饮",
            detail: "12 人餐 · 按每天三餐的常规消费估算",
            minimum: 360,
            maximum: 780,
          },
          {
            category: "门票",
            detail: "故宫、天坛、国家博物馆、景山 · 2 人",
            minimum: 154,
            maximum: 192,
          },
        ],
      },
      v2: {
        midpoint: 1350,
        minimum: 910,
        maximum: 1790,
        items: [
          {
            category: "住宿",
            detail: "前门示例住宿 · 1 间夜",
            minimum: 350,
            maximum: 550,
          },
          {
            category: "交通",
            detail: "4 个活动 · 演示快照按相同市内段数估算",
            minimum: 60,
            maximum: 300,
          },
          {
            category: "餐饮",
            detail: "12 人餐 · 按每天三餐的常规消费估算",
            minimum: 360,
            maximum: 780,
          },
          {
            category: "门票",
            detail: "故宫、国家博物馆、首都博物馆、北京天文馆 · 2 人",
            minimum: 140,
            maximum: 160,
          },
        ],
      },
    },
  };
})();
